### Init
GET http://127.0.0.1:1515

### Test presence
POST http://127.0.0.1:1515/server/update_presence
Content-Type: application/json

{
    "ip": "127.0.0.1",
    "xuid": "2535443051462686",
    "api_activity": {
        "state": "test",
        "details": "test"
    },
    "connection": {
        "ip": "127.0.0.1",
        "network": "localhost",
        "server": "Development"
    }
}

### Offline
POST http://127.0.0.1:1515/server/offline
Content-Type: application/json

{
    "ip": "127.0.0.1",
    "xuid": "2535443051462686",
    "api_activity": {
        "state": "test",
        "details": "test"
    }
}
