# Environment variable named 'PRESENCE_MAN_NETWORK' overwrites this value.
network: "localhost"
# Environment variable named 'PRESENCE_MAN_SERVER_NAME' overwrites this value.
server: "Development-Server"
