network: "localhost" # Environment variable named 'PRESENCE_MAN_NETWORK' overwrites this value.
server-name: "Development-Server" # Environment variable named 'PRESENCE_MAN_SERVER_NAME' overwrites this value.
